### ISSUE TITLE
plot axes values

### ISSUE THREAD

**Issue by davidfombella** [microsoft/PowerBI-visuals-RadarChart#40]
Plot values/ Labels should be good, and the possibility to customize dynamic axes scale

**Comment by helen508light** [comment]
Hi, very similar to your wishes scale behavior  has been implemented on LineDot chart.
Take a look on xAxisProperties processing and then rendering axis.
For numerical scale similar behavior has been implemented there https://github.com/Microsoft/powerbi-visuals-linedotChart
In general, you need to calculate axisProperties influenced by you data, then scale it as in the way similar to this visuals code, and maybe use formatting utils for specific number formats

For dynamic scales dependent on formatting settings, u need to specify this settings as usual in capabilities, settings.ts https://microsoft.github.io/PowerBI-visuals/docs/concepts/capabilities/
